In [179]:
# Importando bibliotecas
import numpy as np
import pandas as pd
import json

In [180]:
# Abrir o arquivo JSON e carregar os dados
with open('teste.json', 'r') as archive_json:
    request_body = json.load(archive_json)

# Acessar a matriz dentro do arquivo JSON
user_data = list(request_body['users'])

print("Usuarios:")
for linha in user_data:
    print(linha)

Usuarios:
{'id': '1qwdcTgFeYU5K07GHcpg', 'data': {'disp': 5, 'ct': 13, 'skill': [{'assembly': 7, 'office': 10, 'git': 5, 'ruby': 1, 'linux': 7, 'java': 3, 'php': 1, 'javascript': 10, 'python': 9, 'sql': 9}]}}
{'id': '2lS4yddcgot3W6qewrAC', 'data': {'disp': 23, 'ct': 12, 'skill': [{'ruby': 3, 'sql': 3, 'javascript': 2, 'office': 8, 'python': 6, 'java': 1, 'assembly': 6, 'git': 4, 'php': 9, 'linux': 5}]}}
{'id': '49wZ4zez5HCP7cgl8ZPs', 'data': {'disp': 0, 'ct': 2, 'skill': [{'java': 6, 'assembly': 10, 'ruby': 3, 'php': 7, 'python': 9, 'office': 3, 'sql': 1, 'git': 3, 'linux': 8, 'javascript': 4}]}}
{'id': 'J3xKLphGMBXtlt3zpdoV', 'data': {'disp': 1, 'ct': 10, 'skill': [{'sql': 7, 'ruby': 5, 'assembly': 1, 'php': 5, 'python': 0, 'javascript': 7, 'git': 9, 'linux': 5, 'office': 5, 'java': 4}]}}
{'id': 'TaVGW6yBTdvemFDQjgqV', 'data': {'disp': 11, 'ct': 8, 'skill': [{'office': 4, 'python': 8, 'ruby': 9, 'php': 5, 'java': 5, 'sql': 4, 'linux': 6, 'assembly': 10, 'git': 9, 'javascript': 6}]}}
{

In [181]:
# Inicializar listas para cada coluna da matriz
ids = []
disp = []
ct = []
php = []
office = []
java = []
javascript = []
python = []
ruby = []
assembly = []
sql = []
git = []
linux = []

# Preencher listas com os dados do JSON
for user in user_data:
    ids.append((user["id"]))  # Manter a coluna de ids como string
    disp.append(int(user["data"]["disp"]))
    ct.append(int(user["data"]["ct"]))
    php.append(int(user["data"]["skill"][0]["php"]))
    office.append(int(user["data"]["skill"][0]["office"]))
    java.append(int(user["data"]["skill"][0]["java"]))
    javascript.append(int(user["data"]["skill"][0]["javascript"]))
    python.append(int(user["data"]["skill"][0]["python"]))
    ruby.append(int(user["data"]["skill"][0]["ruby"]))
    assembly.append(int(user["data"]["skill"][0]["assembly"]))
    sql.append(int(user["data"]["skill"][0]["sql"]))
    git.append(int(user["data"]["skill"][0]["git"]))
    linux.append(int(user["data"]["skill"][0]["linux"]))

# Criar a matriz usando NumPy
matrix = np.array([range(0, len(ids)), disp, ct, php, office, java, javascript, python, ruby, assembly, sql, git, linux]).T


# Exibir a matriz
for row in matrix:
    print(row)

print(ids)

[ 0  5 13  1 10  3 10  9  1  7  9  5  7]
[ 1 23 12  9  8  1  2  6  3  6  3  4  5]
[ 2  0  2  7  3  6  4  9  3 10  1  3  8]
[ 3  1 10  5  5  4  7  0  5  1  7  9  5]
[ 4 11  8  5  4  5  6  8  9 10  4  9  6]
[ 5 19  7  5  7 10  9  6  5  8  7  9  1]
[ 6  2 30  2  6  3  5  5  2  0  1  7  5]
[ 7 10  0  5  2  5  6  1  6  2  2  1  9]
[ 8 30  8  2 10  7  9  7 10  2  9 10  1]
[ 9 12  2  5  7  8  1  0  3  8  8  1  1]
['1qwdcTgFeYU5K07GHcpg', '2lS4yddcgot3W6qewrAC', '49wZ4zez5HCP7cgl8ZPs', 'J3xKLphGMBXtlt3zpdoV', 'TaVGW6yBTdvemFDQjgqV', 'YcutVtAiqMt9R6IgGS2M', 'bSA4wzwwENyXiiFWzcQ8', 'X6HHWLeWjcmv4Afu5rP5', 'Ra1oD5GWqv35RCnpV0WK', 'IovKkezSxG92L62oEeoL']


In [182]:
# Dicionário mapeando habilidades para índices
index = {
    'php': 3,
    'office': 4,
    'java': 5,
    'javascript': 6,
    'python': 7,
    'ruby': 8,
    'assembly': 9,
    'sql': 10,
    'git': 11,
    'linux': 12
}

In [183]:
# Acessar as habilidades requeridas dentro do arquivo JSON
task_json = list(request_body['tarefas'])
print(task_json)

['python', 'php', 'java']


In [184]:
# Resgatar os índices correspondentes às habilidades requeridas
skills_index = [index[skill] for skill in task_json]
print(skills_index)

[7, 3, 5]


In [185]:
# Nova matriz apenas com as habilidades requeridas
users_skills = matrix[:, skills_index]

# Adicionar as três primeiras colunas de volta à nova matriz
users_skills = np.concatenate((matrix[:, :3], users_skills), axis=1)

print("Habilidades requeridas:")
print(users_skills)

Habilidades requeridas:
[[ 0  5 13  9  1  3]
 [ 1 23 12  6  9  1]
 [ 2  0  2  9  7  6]
 [ 3  1 10  0  5  4]
 [ 4 11  8  8  5  5]
 [ 5 19  7  6  5 10]
 [ 6  2 30  5  2  3]
 [ 7 10  0  1  5  5]
 [ 8 30  8  7  2  7]
 [ 9 12  2  0  5  8]]


In [186]:
# Contar quantas linhas têm pelo menos um valor 0 (com exceção três primeiras, que representam o index, a disp e a carga de trabalho)
lines_with_zeros = np.sum(np.any(users_skills[:, 3:] == 0, axis=1))

# Verificar se a quantidade de linhas com zero é igual ou muito próxima ao total de linhas
limite_proximidade = 0.2  # 20% de tolerância para proximidade
if lines_with_zeros == 0:
    verif_dom = users_skills.shape[0]
    print("Não foram removidas linhas - Nenhuma linha contém 0")
    print(users_skills)
else:
    if lines_with_zeros < len(users_skills) * (1 - limite_proximidade):
        # Remover as linhas com pelo menos um valor 0
        users_skills = users_skills[~np.any(users_skills[:, 3:] == 0, axis=1)]
        verif_dom = users_skills.shape[0]
        print("Algumas linhas removidas:")
        print(users_skills)
    else:
        verif_dom = users_skills.shape[0]
        print("Não foram removidas linhas - A quantidade de linhas com 0 é próxima a quantidade de usuários.")
        print(users_skills)

print("Quant. de usuários remanescentes:", verif_dom)

Algumas linhas removidas:
[[ 0  5 13  9  1  3]
 [ 1 23 12  6  9  1]
 [ 2  0  2  9  7  6]
 [ 4 11  8  8  5  5]
 [ 5 19  7  6  5 10]
 [ 6  2 30  5  2  3]
 [ 7 10  0  1  5  5]
 [ 8 30  8  7  2  7]]
Quant. de usuários remanescentes: 8


In [187]:
# Criando matriz vazia para salvar resultados
distances_results = np.zeros((verif_dom, 1))

#Criar vetor com a quantidade de posições igual a quantidades de habilidades requeridas
skills_quant = len(skills_index)
skills_max = np.full(skills_quant, 10)

# Nova matriz apenas com as habilidades requeridas
skills_dist = users_skills[:, 3:]

for i in range(verif_dom):
  user_current = skills_dist[i, :]
  user_current_reshaped = user_current.reshape(1, -1)
  skills_max_reshaped = skills_max.reshape(1, -1)
  variation = user_current_reshaped - skills_max_reshaped
  distance = np.linalg.norm(variation)
  distances_results[i, 0] = distance

print(distances_results)

[[11.44552314]
 [ 9.89949494]
 [ 5.09901951]
 [ 7.34846923]
 [ 6.40312424]
 [11.74734012]
 [11.44552314]
 [ 9.05538514]]


In [188]:
# Juntando os resultados de similaridade com a disponibilidade e a carga de trabalho
disp_cargat = users_skills[:, :3]
verif_dom = np.hstack((disp_cargat, distances_results))
print(verif_dom)

[[ 0.          5.         13.         11.44552314]
 [ 1.         23.         12.          9.89949494]
 [ 2.          0.          2.          5.09901951]
 [ 4.         11.          8.          7.34846923]
 [ 5.         19.          7.          6.40312424]
 [ 6.          2.         30.         11.74734012]
 [ 7.         10.          0.         11.44552314]
 [ 8.         30.          8.          9.05538514]]


In [189]:
# Função para encontrar os usuários não dominados e atualizar a matriz
def find_and_update_non_dominated(df):
    non_dominated_users = []
    
    for idx, row in df.iterrows():
        filtered = df[(df['Disponibilidade'] >= row['Disponibilidade']) &
                      (df['Carga_de_Trabalho'] <= row['Carga_de_Trabalho']) &
                      (df['Habilidade'] <= row['Habilidade'])]

        if len(filtered) == 1:
            non_dominated_users.append(int(row['ID']))

    # Atualizar o ranking com os IDs dos usuários não dominados
    ranking.extend(non_dominated_users)
    
    # Remover usuários não dominados do DataFrame
    df_filtered = df[~df['ID'].isin(non_dominated_users)]
    
    return df_filtered

# Criando um DataFrame com os dados
columns = ['ID', 'Disponibilidade', 'Carga_de_Trabalho', 'Habilidade']
df = pd.DataFrame(verif_dom, columns=columns)

# Lista para armazenar o ranking
ranking = []

# Repetir até que a matriz esteja vazia
while not df.empty:
    df = find_and_update_non_dominated(df)

# Resultado final
print("Ranking dos usuários (IDs ordenados):", ranking)

Ranking dos usuários (IDs ordenados): [2, 5, 7, 8, 1, 4, 0, 6]


In [190]:
# Seus arrays
ranking = np.array(ranking)
ids = np.array(ids)

# Criar o array reorganizado
lst_ranking = ids[ranking]

# Exibir o array reorganizado
print(lst_ranking)

['49wZ4zez5HCP7cgl8ZPs' 'YcutVtAiqMt9R6IgGS2M' 'X6HHWLeWjcmv4Afu5rP5'
 'Ra1oD5GWqv35RCnpV0WK' '2lS4yddcgot3W6qewrAC' 'TaVGW6yBTdvemFDQjgqV'
 '1qwdcTgFeYU5K07GHcpg' 'bSA4wzwwENyXiiFWzcQ8']
