In [4]:
# Importando bibliotecas
import numpy as np
import json

In [5]:
# Abrir o arquivo JSON e carregar os dados
with open('db.json', 'r') as archive_json:
    request_body = json.load(archive_json)

# Acessar a matriz dentro do arquivo JSON
data_json = request_body['users']

print("Usuarios:")
for linha in data_json:
    print(linha)

Usuarios:
{'id': '01', 'disp': 1, 'ct': 10, 'skill': [{'php': 5, 'office': 5, 'java': 4, 'javascript': 7, 'python': 0, 'ruby': 5, 'assembly': 1, 'sql': 7, 'git': 9, 'linux': 5}]}
{'id': '02', 'disp': 11, 'ct': 8, 'skill': [{'php': 5, 'office': 4, 'java': 5, 'javascript': 6, 'python': 8, 'ruby': 9, 'assembly': 10, 'sql': 4, 'git': 9, 'linux': 6}]}
{'id': '03', 'disp': 5, 'ct': 13, 'skill': [{'php': 1, 'office': 10, 'java': 3, 'javascript': 10, 'python': 9, 'ruby': 1, 'assembly': 7, 'sql': 9, 'git': 5, 'linux': 7}]}
{'id': '04', 'disp': 19, 'ct': 7, 'skill': [{'php': 5, 'office': 7, 'java': 10, 'javascript': 9, 'python': 6, 'ruby': 5, 'assembly': 8, 'sql': 7, 'git': 9, 'linux': 1}]}
{'id': '05', 'disp': 2, 'ct': 30, 'skill': [{'php': 2, 'office': 6, 'java': 3, 'javascript': 5, 'python': 5, 'ruby': 2, 'assembly': 0, 'sql': 1, 'git': 7, 'linux': 5}]}
{'id': '06', 'disp': 10, 'ct': 0, 'skill': [{'php': 5, 'office': 2, 'java': 5, 'javascript': 6, 'python': 1, 'ruby': 6, 'assembly': 2, 'sql':

In [6]:
# Extrair valores de 'disp', 'ct' e 'skill' e criar a matriz
matrix = []
for idx, user in enumerate(data_json, start=1):
    disp_ct_values = [user['disp'], user['ct']]
    skill_values = user['skill'][0]
    values = [idx] + disp_ct_values + [skill_values[key] for key in skill_values]
    matrix.append(values)

# Converter a matriz para um array NumPy
users_data = np.array(matrix)

# Imprimir a matriz resultante
print(users_data)

[[ 1  1 10  5  5  4  7  0  5  1  7  9  5]
 [ 2 11  8  5  4  5  6  8  9 10  4  9  6]
 [ 3  5 13  1 10  3 10  9  1  7  9  5  7]
 [ 4 19  7  5  7 10  9  6  5  8  7  9  1]
 [ 5  2 30  2  6  3  5  5  2  0  1  7  5]
 [ 6 10  0  5  2  5  6  1  6  2  2  1  9]
 [ 7 30  8  2 10  7  9  7 10  2  9 10  1]
 [ 8 12  2  5  7  8  1  0  3  8  8  1  1]
 [ 9  8  9 10  3  0  9  4  6  9  3  2  1]
 [10 16  7  0  7  6  0  4  8 10  1  8  1]
 [11 23 15  1  0  1  2 10  8  8  4  5  5]
 [12  0  2  7  3  6  4  9  3 10  1  3  8]
 [13  1 17  3  4  1  1  9  9  1  7  3 10]
 [14 12 22  0  5  3  6  8 10  8  4  6  9]
 [15 16 18  1  4  5  3 10  1  2  9  2  8]
 [16 11  1  4  9  3  6 10  7  9  3  9 10]
 [17 23 12  9  8  1  2  6  3  6  3  4  5]
 [18 11 21  4  6  1  1  9  4  2  7  0  5]
 [19 27 20  4  2  6  0  4  8  9  0  8  5]
 [20 16 10  9  8 10 10  6  8  7  5  7  2]]


In [7]:
# Dicionário mapeando habilidades para índices
index = {
    'php': 3,
    'office': 4,
    'java': 5,
    'javascript': 6,
    'python': 7,
    'ruby': 8,
    'assembly': 9,
    'sql': 10,
    'git': 11,
    'linux': 12
}

In [8]:
# Acessar as habilidades requeridas dentro do arquivo JSON
task_json = request_body['tarefa']
print(task_json)

['python', 'php', 'ruby']


In [9]:
# Resgatar os índices correspondentes às habilidades requeridas
skills_index = [index[skill] for skill in task_json]
print(skills_index)

[7, 3, 8]


In [10]:
# Nova matriz apenas com as habilidades requeridas
users_skills = users_data[:, skills_index]

# Adicionar as três primeiras colunas de volta à nova matriz
users_skills = np.concatenate((users_data[:, :3], users_skills), axis=1)

print("Habilidades requeridas:")
print(users_skills)

Habilidades requeridas:
[[ 1  1 10  0  5  5]
 [ 2 11  8  8  5  9]
 [ 3  5 13  9  1  1]
 [ 4 19  7  6  5  5]
 [ 5  2 30  5  2  2]
 [ 6 10  0  1  5  6]
 [ 7 30  8  7  2 10]
 [ 8 12  2  0  5  3]
 [ 9  8  9  4 10  6]
 [10 16  7  4  0  8]
 [11 23 15 10  1  8]
 [12  0  2  9  7  3]
 [13  1 17  9  3  9]
 [14 12 22  8  0 10]
 [15 16 18 10  1  1]
 [16 11  1 10  4  7]
 [17 23 12  6  9  3]
 [18 11 21  9  4  4]
 [19 27 20  4  4  8]
 [20 16 10  6  9  8]]


In [11]:
# Contar quantas linhas têm pelo menos um valor 0 (com exceção três primeiras, que representam o index, a disp e a carga de trabalho)
lines_with_zeros = np.sum(np.any(users_skills[:, 3:] == 0, axis=1))

# Verificar se a quantidade de linhas com zero é igual ou muito próxima ao total de linhas
limite_proximidade = 0.2  # 20% de tolerância para proximidade
if lines_with_zeros == 0:
    users = users_skills.shape[0]
    print("Não foram removidas linhas - Nenhuma linha contém 0")
    print(users_skills)
else:
    if lines_with_zeros < len(users_skills) * (1 - limite_proximidade):
        # Remover as linhas com pelo menos um valor 0
        users_skills = users_skills[~np.any(users_skills[:, 3:] == 0, axis=1)]
        users = users_skills.shape[0]
        print("Algumas linhas removidas:")
        print(users_skills)
    else:
        users = users_skills.shape[0]
        print("Não foram removidas linhas - A quantidade de linhas com 0 é próxima a quantidade de usuários.")
        print(users_skills)

print("Quant. de usuários remanescentes:", users)

Algumas linhas removidas:
[[ 2 11  8  8  5  9]
 [ 3  5 13  9  1  1]
 [ 4 19  7  6  5  5]
 [ 5  2 30  5  2  2]
 [ 6 10  0  1  5  6]
 [ 7 30  8  7  2 10]
 [ 9  8  9  4 10  6]
 [11 23 15 10  1  8]
 [12  0  2  9  7  3]
 [13  1 17  9  3  9]
 [15 16 18 10  1  1]
 [16 11  1 10  4  7]
 [17 23 12  6  9  3]
 [18 11 21  9  4  4]
 [19 27 20  4  4  8]
 [20 16 10  6  9  8]]
Quant. de usuários remanescentes: 16


In [12]:
# Criando matriz vazia para salvar resultados
distances_results = np.zeros((users, 1))

#Criar vetor com a quantidade de posições igual a quantidades de habilidades requeridas
skills_quant = len(skills_index)
skills_max = np.full(skills_quant, 10)

# Nova matriz apenas com as habilidades requeridas
skills_dist = users_skills[:, 3:]

for i in range(users):
  user_current = skills_dist[i, :]
  user_current_reshaped = user_current.reshape(1, -1)
  skills_max_reshaped = skills_max.reshape(1, -1)
  variation = user_current_reshaped - skills_max_reshaped
  dintance = np.linalg.norm(variation)
  distances_results[i, 0] = dintance

print(distances_results)

[[ 5.47722558]
 [12.76714533]
 [ 8.1240384 ]
 [12.36931688]
 [11.04536102]
 [ 8.54400375]
 [ 7.21110255]
 [ 9.21954446]
 [ 7.68114575]
 [ 7.14142843]
 [12.72792206]
 [ 6.70820393]
 [ 8.1240384 ]
 [ 8.54400375]
 [ 8.71779789]
 [ 4.58257569]]


In [13]:
# Juntando os resultados de similaridade com a disponibilidade e a carga de trabalho
disp_cargat = users_skills[:, :3]
verif_dom = np.hstack((disp_cargat, distances_results))
print(verif_dom)

[[ 2.         11.          8.          5.47722558]
 [ 3.          5.         13.         12.76714533]
 [ 4.         19.          7.          8.1240384 ]
 [ 5.          2.         30.         12.36931688]
 [ 6.         10.          0.         11.04536102]
 [ 7.         30.          8.          8.54400375]
 [ 9.          8.          9.          7.21110255]
 [11.         23.         15.          9.21954446]
 [12.          0.          2.          7.68114575]
 [13.          1.         17.          7.14142843]
 [15.         16.         18.         12.72792206]
 [16.         11.          1.          6.70820393]
 [17.         23.         12.          8.1240384 ]
 [18.         11.         21.          8.54400375]
 [19.         27.         20.          8.71779789]
 [20.         16.         10.          4.58257569]]


In [14]:
#lst_ranking = lista com usuários rankeados